### ISSUE TITLE
Add ORCID ids for authors that have them

### ISSUE THREAD

**Issue by dwinter** [ropensci/rentrez#118]
CRAN now displays ORCID links for authors that have them, with the goal to have a stable/unique ID for package authors. https://twitter.com/AchimZeileis/status/917319708713668608

We should add these to the DESCRIPTION file before next CRAN release

**Comment by dwinter** [comment]
@sckott and @htc502 , let me know if you have an ORCID and you want it included.

**Comment by sckott** [comment]
thx @dwinter mine: https://orcid.org/0000-0003-1444-9135

**Comment by htc502** [comment]
Hi @dwinter,

Mine should be https://orcid.org/0000-0001-9277-2507
Thank you.

guangchun
