### ISSUE TITLE
use with a local copy of PubMed

### ISSUE THREAD

**Issue by sbalci** [ropensci/rentrez#130]
Thank you for this package.

Is it possible to use it with a local copy of PubMed?

By a local copy I mean as described here: https://dataguide.nlm.nih.gov/edirect/archive.html

Thank you and Best wishes

**Comment by dwinter** [comment]
Hi sbalci, 

At the moment, rentrez only works with the web api. It might be possible to us to develop a package that duplicates the `edirect` archive in the future, but it would like be some in addition to rentrez. 

I'm closing the issue, but feel free to reply

**Comment by sbalci** [comment]
Thank you.
I already have a local copy. I just want to use R interface and if possible your package to access my local copy like:
`entrez_search(db="MyLocalCopy", term="myQuery")`

Best wishes

**Comment by dwinter** [comment]
Sadly,  `rentrez` just won't be able to do that. It is written to take advantage of the webserver-based access to the databases, as I understand it, the locally stored database can't be accessed in the same way.
