### ISSUE TITLE
how to show pubmed IDs per year 

### ISSUE THREAD

**Issue by ghost** [ropensci/rentrez#135]
curious how to show PubMed IDs per year for a specific search?

ex:
2017 PubmID #
2017 PubmID #
2017 PubmID #
2017 PubmID #
2016 PubmID #
2016 PubmID #
2016 PubmID #
2016 PubmID #

I'm able to plot papers by year, but what i really need is a list of pubmed IDs per year. thoughts?

**Comment by dwinter** [comment]
Apologies for leaving this equestion open for so long (so long even that you have since deleted yout account!). I don't think it is possible to find this via entrez
