### ISSUE TITLE
refseq select id from ENSEMBL id

### ISSUE THREAD

**Issue by cb4github** [ropensci/rentrez#147]
Dear rentrez,

The following command sequence was provided in order to convert the included ENSEMBL id to the corresponding RefSeq Select it using the Entrez Direct client. I'd like to know if it can be implemented exclusively via rentrez.

`esearch -db gene -query 'ENSG00000116260' | elink -target nuccore -name gene_nuccore_refseqrna | efilter -query 'refseq_select[filter]' |  efetch -format acc`

Please advise, thanks.

**Comment by dwinter** [comment]
Sorry for taking so long to respone to this. For the record, something like this would be possible:

```r
gene_search <- entrez_search(db = "gene", term="ENSG00000116260")
gene_links <- entrez_link(dbfrom="gene", db = "nuccore", id = gene_search$ids)
entrez_fetch(db = "nuccore", id=links$links$gene_nuccore_refseqrna, retty="acc")
cat(entrez_fetch(db = "nuccore", id=links$links$gene_nuccore_refseqrna, rettype="acc"), "\n")
```
```sh
NM_001004128.3
NM_002826.5
```

I'm not sure how you'd get down the ref-seq select subset, though
