### ISSUE TITLE
How to get the GEO update list?

### ISSUE THREAD

**Issue by cgh2797** [ropensci/rentrez#149]
Hi, 
I wanted the results  GEO series data,  "Homo sapiens, Expression profiling" by array, also sorted chronologically from oldest also a format to download the list at once.
How can i do with rentrez????

**Comment by dwinter** [comment]
Hi @cgh2797 ,

Apologies for taking so long to reply. Sadly, my knowldege of particular NCBI databases doesn't extend this far. You could try asking the NCBI for help. Though i don't think it's possible to sort data by data for any database. Sorry I couldn't be more help
