### ISSUE TITLE
getting all text data from pubmed articles

### ISSUE THREAD

**Issue by Hilal-Urun** [ropensci/rentrez#176]
Hi, I need to get all text data from fetched id's articles, is it possible with rentrez?  Because when I examined on documents I couldn't see something like that, could you help me please?

**Comment by allenbaron** [comment]
Have you considered using the ropensci [fulltext](https://github.com/ropensci/fulltext) package?

**Comment by Hilal-Urun** [comment]
thanks for your response. yes I saw that but it's written in R, is it possible to use in python too?

**Comment by allenbaron** [comment]
No, you're right. Like rentrez, fulltext is written in R.

**Comment by Hilal-Urun** [comment]
I solved the problem. Thanks a lot. If someone also need getting full text from pmc , I added link [here](https://gist.github.com/Hilal-Urun/7dfe167b369aa735c761f0de717ef06b#file-pmc_fulltext-py)
