### ISSUE TITLE
entrez_link sometimes doesn't return "$nuccore_pubmed"

### ISSUE THREAD

**Issue by niki0211** [ropensci/rentrez#184]
I am trying to download sequences from NCBI and I also want to retrieve some summary info with entrez_summary.

Therefore I am using "entrez_link" but sometimes exactly the same request result in different results.
Specifically the "nuccore_pubmed" value is sometimes not returned but only "nuccore_pubmed_weighted".

Here is an example request with a specific ID.

`linked <- entrez_link(dbfrom = "nucleotide", db = "pubmed", id = "ON597769.1")`

Sometime I get the PubmedId back, sometimes not. See screenshot:

![grafik](https://user-images.githubusercontent.com/37581912/206155127-620a5767-0943-4572-ba99-498484c4d5a1.png)

**Comment by niki0211** [comment]
I also observed that it happens for some IDs more frequently than for others....

**Comment by niki0211** [comment]
Alright, thanks for the hint. I try to compare the result with commandline Entrez Utils but I don't know how to run the same command. Since "elink" does not allow to specify "dbfrom".

**Comment by allenbaron** [comment]
See https://www.ncbi.nlm.nih.gov/books/NBK25499/#_chapter4_ELink_

**Comment by niki0211** [comment]
Thanks for the link. I will use edirect to double-check my results.
However, it seems to be not a problem anymore...It just works fine although I didn't change anything. So maybe you were right and it was some kind of NCBI issue.
