### ISSUE TITLE
Build failing with 502

### ISSUE THREAD

**Issue by dwinter** [ropensci/rentrez#24]
[The build has started to fail at Travis CI](https://travis-ci.org/ropensci/rentrez/builds/41539674) this week, despite no new commits. 

The failing examples work perfectly form my computer, so suspect it's comething funny about the Travis network, but needs to be taken care of

**Comment by sckott** [comment]
@dwinter taking a look

**Comment by sckott** [comment]
hmmm, for some reason this example isn't working https://github.com/ropensci/rentrez/blob/master/R/entrez_summary.r#L40 tried it locally and doesn't work, same error as on Travis I think

your examples in that file at least aren't wrappaed in `\dontrun` so they run (cran recently changed at least in R-dev to actually run exxamples in `\donttest`, so only `\dontrun` works to prevent examples from running on cran checks)

**Comment by dwinter** [comment]
Thanks for the help @sckott -- looking at the rest of the Travis log there are a few other examples I either need to update or wrap with `\dontrun`
