### ISSUE TITLE
Clean up documentation & examples for CRAN release

### ISSUE THREAD

**Issue by dwinter** [ropensci/rentrez#25]
Rentrez is about due a release on CRAN, but needs a little cleaning up first

 * [x] As per #24 one example of `entrez_summary` is failing on Travis: Find out why.
 * [x] Update all `entrez_summary` examples to use the default (Version 2.0) summary records. #20 
 * [x] Documentation for `entrez_citmatch` 
 * [x]  Proof read docs, build windows binary
 * [x] submit to CRAN

**Comment by dwinter** [comment]
Up on CRAN!

**Comment by sckott** [comment]
nice :+1:
