### ISSUE TITLE
Better Vignette

### ISSUE THREAD

**Issue by dwinter** [ropensci/rentrez#28]
The current vignette describes one possible use on rentrez. I'd like to extend it so that it represents a more general introduction to the package and the Eutils API. 

A complete vignette should 
  * describe the `entrez_db*` functions as a way of learning about the API
  * demonstrate simple use-cases like converting IDs
  * point to packages like `fulltext` that make make use on entrez. 
  * uses the current example or something similar to demonstrate a compelte use of the library

**Comment by briatte** [comment]
Dear David,

Would you mind expanding the vignette on how to use `rentrez` to navigate MeSH terms? It would tremendously helpful if `rentrez` could automate some of the manual searches that currently have to be done through the MeSH browser.

**Comment by dwinter** [comment]
Hi @briatte , very happy to. Have even [made a bit of start on searching with them](https://github.com/ropensci/rentrez/blob/new_vignette/vignettes/rentrez_tutorial.Rmd#precise-queries-using-mesh-terms).

Can you explain how you  typically use the MeSH browser now? Might help in writing an automated example

**Comment by briatte** [comment]
Hi @dwinter,

As the NCBI documentation suggests, most PubMed searchers start with a list of keywords that they want to map to MeSH terms (`[mh]`) when possible, or use in a title-abstract search (`[tiab]`) if not.

Here's a quick example of a fuzzy match:

```r
library(rentrez)
library(dplyr)
s = entrez_search(db = "mesh", term = "tobacco", retmax = 99999)
f = entrez_summary(db = "mesh", id = s$ids)
length(f)
62
```

Let's now identify MeSH descriptors in the results:

```r
type = sapply(f, "[[", "ds_recordtype")
types = c("descriptor" = "mh", "supplemental-record" = "nm")
```

And finally, let's identify MeSH SRCs (supplemental record concepts, `[nm]`) in the results, discriminating between those that are mapped by the main descriptors and those that are not:

```r
uids = sapply(f, "[[", "uid")
lids = lapply(f, "[[", "ds_headingmappedtolist")
lids = sapply(lids, function(x) x[ !x %in% uids ])
```

Here's dirty code to compile the results into a data frame:

```
res = lapply(f[ which(type == "descriptor" | length(lids) > 0) ], function(x) {
  data_frame(mesh = x$ds_meshui,
             type = types[ x$ds_recordtype ],
             term = x$ds_meshterms[1],
             #year = x$ds_yearintroduced,
             maps = paste0(x$ds_headingmappedtolist, collapse = ","))
}) %>% bind_rows %>% select(mesh, type, term)
```

Now, if you look at the top of this dataset, you get the MeSH descriptors that correspond to "tobacco":

```
Source: local data frame [6 x 3]

     mesh type                             term
1 D064424   mh                      Tobacco Use
2 D062789   mh                 Tobacco Products
3 D061485   mh   Tobacco Use Cessation Products
4 D025641   mh Tobacco necrosis satellite virus
5 D020340   mh            Tobacco Use Cessation
6 D019460   mh                 Tobacco Industry
```

And if you look at the bottom, you get the MeSH supplementary concepts that are _not_ mapped by these descriptors:

```
Source: local data frame [6 x 3]

     mesh type                                     term
1 C058814   nm                                   germin
2 C058053   nm pheromone-binding protein, Manduca sexta
3 C049909   nm   tobacco mosaic virus protein (103-112)
4 C046039   nm           TGP protein, Nicotiana tabacum
5 C024746   nm                              tobacco tar
6 C009496   nm          H protein, Tobacco mosaic virus
```

From there, it is easy, for instance, to look for PubMed articles on the tobacco industry that also discuss tobacco tar.

Does this sound like a reasonable search approach to you?

Notes:

- the code above won't work straight away if `length(f) == 1`; in that case, you need to `f = list(f)` first
- as you observe somewhere else, `sapply(f, "[[", "column")` is not a very friendly data manipulator

**Comment by dwinter** [comment]
Thanks so much for this -- it will be very helpful in writing up a workflow. 

Hopefully some of the "new stuff" in development will make this easier. Will let you know when I have something :smiley:

**Comment by dwinter** [comment]
This is very nearly there. Still needs a clean up on spelling an grammar and a final section linking to wiki examples and other projects

**Comment by briatte** [comment]
Thanks!

**Comment by dwinter** [comment]
Hi @briatte -- I'm going to close this now, even though your suggestion is not in the vignette.

I want to keep the vignette as brief as possible, so will instead include this example in the github wiki for the this repo (which is mentioned in the vignette and will be mentioned i the README once it's a but more useful). 

Thanks again for the really good use case, and I hope what I've come up with will help you (will tag you when it goes up).
