### ISSUE TITLE
Parse JSON error

### ISSUE THREAD

**Issue by spfarris** [ropensci/rentrez#29]
Keep receiving the following error when using the "entrez_summary"

Error in parseJSON(txt) : lexical error: invalid char in json text.
          gov.",             "status": suppressed,             "idgicl
                     (right here) ------^

**Comment by dwinter** [comment]
Tanks for the report @spfarris, 

In the short term, you can use `entrez_summary(..., version="1.0")` to get the 'old' records in xml. 

As to the bug, fo you get this on all calls to `entrez_summary`? Even the ones in the help messages examples? If not, can you give me a specific query that does this. 

Secondly, can you paste the results of `sessionInfo()` (or, if you have devtools installed `session_info()`)

Thanks, and hope we can get this sorted.

**Comment by dwinter** [comment]
Hi @spfarris -- have you had a moment to check out the details above? 

I'd really like to get the bottom of this bug and ensure it doesn't affect others.

**Comment by dwinter** [comment]
Closing this as un-reproducable.
