### ISSUE TITLE
Clean up README

### ISSUE THREAD

**Issue by dwinter** [ropensci/rentrez#42]
At present, the readme is out of synch with the development version of the package. 

I think that's OK for now, as the readme introduces the version avaliable on CRAN, but it should be updated. 

In addition... it's kind of long. I'd rather is had a few short-sharp examples to get people started. Then links the relevant vignette sections for more detail

**Comment by htc502** [comment]
tried the code of the new 1.0 version on both win and linux, it runs smoothly~_~.
thanks you..
