### ISSUE TITLE
Helpful error message for over-long requests

### ISSUE THREAD

**Issue by dwinter** [ropensci/rentrez#46]
See #45:

The Eutils api has a maximum size for a URL, and will return an error if try to make a larger one. At the moment `rentrez` just passes on the `httr` error which itself is gathered from the NCBI's message. 

We should either
* Check the URL length prior to making the call
* Return a more helpful message (i.e. use webenvs or entrez_post) after hitting 414

**Comment by akshaynagpal** [comment]
We can give a link to the 'webenv' tutorial/documentation page in the error message so that it will be a quick solution as compared to the user searching for the 'webenv' manually.
