### ISSUE TITLE
entrez_search error 

### ISSUE THREAD

**Issue by FrVan** [ropensci/rentrez#59]
Hi David,

I have used rentrez in the past without any problems but all of a sudden I get the following error when I try to run an entrez_search (even with the examples from the tutorial):
Error in as.vector(x, "character") : 
  cannot coerce type 'externalptr' to vector of type 'character'

I am running R version 3.2.2 and have already tried to install the latest rentrez version (0.5.1) again but keep getting the error. Do you have any idea what might be wrong? 

Thank you very much,
Frank

**Comment by FrVan** [comment]
Hi David,

After posting the issue I noticed that the NCBI servers were down. Everything seems to be working fine now.

Frank

**Comment by dwinter** [comment]
Glad this sorted itself out @FrVan -- it would be nice the NCBI had a standard message for these cases that rentrez could pass on, but it doesn't seem to :confused:
