### ISSUE TITLE
extract_form_esummary matrix cannot be cleanly written to csv

### ISSUE THREAD

**Issue by Monty9** [ropensci/rentrez#65]
Hi David,
Below is the example. I did not understand why title, fulljournalname, pubtype has the text data extends to second column. 
```
PM.ID <- c("26287849", "25979833", "25667274", "25430497", "24968756", "24846037", "24296758", "24281417", "24128713", "24055406","23489023")
p.data <- entrez_summary(db = "pubmed", id = PM.ID  )
pubrecord.table <- extract_from_esummary(esummaries = p.data , elements = c("uid","title","fulljournalname", "pubtype", "volume", "issue", "pages",                                                                           "lastauthor","pmcrefcount", "issn", "pubdate" ))
is(pubrecord.table) #  "matrix"         "array"          "structure"      "vector"         "vectorORfactor"
pubrecord.table <- t(pubrecord.table) # transpose the rows into columns
write.csv(pubrecord.table , file = "test12.csv" )
```

**Comment by dwinter** [comment]
This is not really a problem with rentrez, just a property of NCBI records and R objects. 

In this case, the pubtype field is variably-sized:
```r
sapply(pubrecord.table[4,], length)
```
```
26287849 25979833 25667274 25430497 24968756 24846037 24296758 24281417 
       2        2        1        2        1        3        1        2 
24128713 24055406 23489023 
       1        2        2 
```

When you try and write the matrix it represents the vectrors like you'd type them in (`c(..., ...)`) which adds a comma which breaks the csv format. 

In this case, you can collapse the vectors:

```r
pubrecord.table[4,] <- sapply(pubrecord.table[4,], paste, collapse=" & ")
```
and unlist each matrix row to allow them to be written out

```r
f <- tempfile()
write.csv( apply(pubrecord.table, 1, unlist), f)
re_read <- read.csv(f)
re_read$pmcrefcount
```

```
 [1]  0  1  3  2  1 26 10  4  3  2 21
```

**Comment by Monty9** [comment]
Hi david,
The solution above works on certain PMID queries, but for others I still get an error. Depending on PMID the variable field lengths are noted in Title, Journal name , pubtype or something else. I thought just removing the row number will fix the issue. But, I get error when trying to write a table on Rshiny
`pubrecord.table[,] <- sapply(pubrecord.table[,], paste, collapse=" & ")` 
But, I get an error 
`Error in apply(pubrecord.reference, 1, unlist) : dim(X) must have a positive length` 
P.S Why was the function  `extract_form_esummary` designed to return a matrix ? The data it extracts is a mix of character, string and so by definition dataframe would ideal to store these kind of data, while matrix is is expected to store data of the same type ?

**Comment by dwinter** [comment]
I'm not sure what you are trying to in the example, but it seems like it's hitting empty fields?

`extract_form_esummary ` is really a wrapper to `sapply`, it doesn't return `data.frames` because I think most users don't expect `data.frame` columns to contain _vectors_ like 

```r
df <- as.data.frame(t(pubrecord.table))
df$pubtype
```

```
$`26287849`
[1] "Journal Article"   "Multicenter Study"

$`25979833`
[1] "Journal Article"             "Randomized Controlled Trial"

$`25667274`
[1] "Journal Article"
.
.
.
```

Structured data like that would seem to fit a list better than a `data.frame`, and you can get that by setting `simplify=FALSE`.

**Comment by Monty9** [comment]
Hi David,
I think you are probably right david. One search is resulting in empty values for many fields. It is probably when the search hits empty an field it is throwing the error.  Is there a way to address this ? 

```
# search 1 ---- 5 PMID with empty values in fields of Volume, issue pages and few 
PM.ID <- c("26391251","26372702","26372699","26371045","26338018","26317919",
           "26315966","26301800","26301799","26258891") # does not output table on Rshiny

# search 2 ----Only Empty field for ISSN for PMID 24348463..However, it did not throw an error. 
PM.ID <- c("26386083","26273372","26066373","25837167","25466451","25013473",
           "24888229","24348463","24071017","24019382") # outputs table

p.data <- entrez_summary(db = "pubmed", id = PM.ID  )
pubrecord.table <- extract_from_esummary(esummaries = p.data ,
                                         elements = c("uid","title",
                                                      "fulljournalname",
                                                      "pubtype", "volume",
                                                      "issue","pages",
                                                      "lastauthor",
                                                      "pmcrefcount",
                                                      "issn","pubdate"))

pubrecord.table[,] <- sapply(pubrecord.table[,], paste, collapse = "&")
write.csv(pubrecord.extract, file = "test.csv")
pubrecord.table <- apply(pubrecord.table, 1, unlist)
```

**Comment by dwinter** [comment]
OK, good luck to getting to the bottom of the shiny problem :)
