### ISSUE TITLE
entrez_search

### ISSUE THREAD

**Issue by FranzKrah** [ropensci/rentrez#69]
Hello,

I installed rentrez under R version 3.2.2. And I have the following Error when following the example...

> library("rentrez")
> hox_paper <- entrez_search(db="pubmed", term="10.1038/nature08789[doi]")
Error in as.vector(x, "character") : 
  cannot coerce type 'externalptr' to vector of type 'character'

Please help.
All the Best,
Franz

**Comment by dwinter** [comment]
Hi @FranzKrah, 

These "external pointer" errors often come up when the NCBI is down for a while. I've just checked and the example works for me now -- can you test that you still get this error. 

If you do, can you paste in the output of `traceback()` run right after the error?

Thanks

**Comment by FranzKrah** [comment]
Hi, it worked, thanks!! 

Cheers,
Franz



Franz-Sebastian Krah
PhD student, Fungal Ecology and Evolution
Plant Biodiversity Research Group
Technische Universität München (TUM)
Mobile: 0170 5221189
Personal Website <http://franzkrah.github.io/> and University Website <http://www.biodiv.wzw.tum.de/index.php?id=18>
