### ISSUE TITLE
Error in ans[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by andzandz11** [ropensci/rentrez#84]
What is happening?

snail_coi <- entrez_search(db="nuccore", term="COI[Gene] AND Gastropoda[ORGN]", use_history=TRUE)
Error in ans[[1]] : subscript out of bounds

query <- "Gastropoda[Organism] AND COI[Gene]"
entrez_search(db="nuccore", term=query, use_history=TRUE,retmode="json")
Error in if (nchar(x$QueryTranslation) > 50) { : argument has length 0

It's completely broken :(

**Comment by andzandz11** [comment]
It turns out thet nuccore is down! The world is ending!

http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=nucleotide&term=biomol+trna[prop]

**Comment by htc502** [comment]
Hi @dwinter ,I think it's better to add an extra feature that is able to notify the user when the database is down. error information like this is quite misleading...

**Comment by dwinter** [comment]
Hi @htc502 -- I agree, unfortunately this is one of those "[Happy families are all alike; every unhappy family is unhappy in its own way](https://en.wikipedia.org/wiki/Anna_Karenina_principle)" situations. There are many different ways in which the NCBI might return "intermittent" errors and Eutils doesn't flag them in a consistent way. 

If there are specific examples we can catch we should. In the mean time we should include a not about intermittent outages in vignette, encouring bug reports by making the point that sometimes it will fix itself before we look at it
