### ISSUE TITLE
put NEWS bits in releases

### ISSUE THREAD

**Issue by sckott** [ropensci/rentrez#93]
hey @dwinter - We want all rOpenSci pkgs to consistently keep track of changes for each CRAN release, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  

- you already keep a `NEWS` file, thanks!
- looks like the last two releases didn't get git tagged, could you do that?
- You have used the [releases tab](https://github.com/ropensci/clifro/releases) on this repo to include the associated NEWS items for each tag/version in the past - thanks for that, but can you make sure to always git tag each release, and put the NEWS items in each release in the releases tab? e.g., right now CRAN is at version `1.0.4`, while most recent release is at `1.0.2` -  thanks! 😄

**Comment by dwinter** [comment]
Hey @sckott -- sorry the delay in getting on to this. Will do it today.
