### ISSUE TITLE
question about querying a sequence

### ISSUE THREAD

**Issue by yukund** [ropensci/rentrez#94]
Hi rentrez team

I would like to search a sequence via your rentrez tool

I have tried entrez_search with db name and term. However it does not return any results. see details
```
entrez_search(db="nucleotide", term="ACAACACACACCCACACACACAACACACCAA")
Entrez search result with 0 hits (object contains 0 IDs and no web_history object)
 Search term (as translated):  (ACAACACACACCCACACACACAACACACCAA[All Fields])  
```
Basically,  I want to do 
![capture](https://cloud.githubusercontent.com/assets/4123840/21035511/89367708-be24-11e6-99be-6c218081e596.PNG)

Any suggestions will be appreciated.
Thanks
Yanbo

**Comment by dwinter** [comment]
Hi @yukund , sadly rentrez doesn't work with BLAST. 

I'm not sure there is a good package for the NCBI blast API in R. If you are comfortable with python you could try Biopython ( @Biopython), that project has a nice wrapper in Bio.BLAST.NCBIWWW.

**Comment by yukund** [comment]
sure, thank you , I will have a look at BioPython.
